Update linux.yml

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -129,26 +129,26 @@ jobs:
           -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF \
           $DEFINE
 
-      - name: Check.
-        if: env.ONLY_CACHE == 'false'
-        run: |
-          filePath="out/Release/Telegram"
-          if test -f "$filePath"; then
-            echo "Build successfully done! :)"
+      # - name: Check.
+      #   if: env.ONLY_CACHE == 'false'
+      #   run: |
+      #     filePath="out/Release/Telegram"
+      #     if test -f "$filePath"; then
+      #       echo "Build successfully done! :)"
 
-            size=$(stat -c %s "$filePath")
-            echo "File size of ${filePath}: ${size} Bytes."
-          else
-            echo "Build error, output file does not exist."
-            exit 1
-          fi
+      #       size=$(stat -c %s "$filePath")
+      #       echo "File size of ${filePath}: ${size} Bytes."
+      #     else
+      #       echo "Build error, output file does not exist."
+      #       exit 1
+      #     fi
 
       - name: Move artifact.
         if: env.UPLOAD_ARTIFACT == 'true'
         run: |
           cd out/Release
           mkdir artifact
-          mv {Telegram,Updater} artifact/
+          mv * artifact/
       - uses: actions/upload-artifact@v4
         if: env.UPLOAD_ARTIFACT == 'true'
         name: Upload artifact.
